name: dart_mssql
description: r2dbc-mssql Dart implementation.
version: 0.0.1
repository: https://github.com/pheonixeye/dart_mssql.git
publish_to: none

environment:
  sdk: ^3.1.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dartedious_spi:
    path: C:\Users\KareemZaher\Desktop\darTedious\dartedious_spi
  rxdart:
  bit_array:  
  duffer: 


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
